{% set name = "aiohttp-socks" %}
{% set version = "0.9.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/aiohttp_socks-{{ version }}.tar.gz
  sha256: 5b320d1bb156fc56d0b31f9de8d5b9b0affbcf1f2df9b8172334dc10e63e4e2f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - aiohttp >=2.3.2
    - async-timeout
    - python >=3.6
    - python-socks >=2.4.3,<3.0.0

test:
  imports:
    - aiohttp_socks
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/aiohttp-socks
  summary: Proxy connector for aiohttp
  license: Apache-2.0
  license_file: LICENSE.txt
  dev_url: https://github.com/romis2012/aiohttp-socks

extra:
  recipe-maintainers:
    - goanpeca
